version: '3'
services:
  webapp:
    build: ./front_end_animerec
    image: webapp:latest
    container_name: webapp
    ports:
      - "5000:5000"
    volumes:
      - "/home/nvidia/Desktop/AnimeRec/front_end_animerec:/front_end_animerec"
    deploy:
      resources:
        limits:
          cpus: '0.20'
          memory: 200M
  
  api:
    build: ./anime-recommendation-system
    image: api:latest
    container_name: api
    ports:
      - "8000:8000"
    volumes:
      - "/home/nvidia/Desktop/AnimeRec/anime-recommendation-system:/api"
  
  react:
    build: ./front_end_animerec/react_code
    image: react:latest
    container_name: react
    ports:
      - "3000:3000"
    volumes:
      - "/home/nvidia/Desktop/AnimeRec/front_end_animerec/react_code:/react_code"